version: '3.8'

services:
  api-proxy:
    image: terrysiu/api-proxy:latest
    ports:
      - "5000:5000"
    volumes:
      - ./config:/app/config
    restart: unless-stopped
    environment:
      - CONFIG_PATH=/app/config/config.json